FROM public.ecr.aws/lambda/python:3.11

# Set working directory to /function
WORKDIR /function

# Copy function code
COPY src/ ${LAMBDA_TASK_ROOT}/

# Copy requirements.txt and install dependencies
COPY requirements.txt .
RUN pip install -r requirements.txt -t ${LAMBDA_TASK_ROOT}

# Set runtime interface client as default command for the container runtime
CMD ["main.handler"]

