name: (Python API) - Terraform Deploy

on:
  push:
    branches: 
      - master

permissions:
  id-token: write
  contents: read
  pull-requests: write

env:
  TF_LOG: INFO
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: us-east-1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose

    - name: Login to Amazon ECR
      id: ecr-login
      uses: aws-actions/amazon-ecr-login@v1

    - name: Set Up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.8.5

    - name: Initialize Terraform
      run: |
        cd infrastructure/stages/prod
        terraform init -var-file=variables.tfvars -upgrade

    - name: Plan Terraform
      run: |
        cd infrastructure/stages/prod
        terraform plan -var-file=variables.tfvars

    - name: Apply Terraform Changes
      run: |
        cd infrastructure/stages/prod
        terraform apply -var-file=variables.tfvars -auto-approve